variables:
    VPC_NAME:
        default: test-vpc
        description: The name of the VPC that this server is to be created in
        overrides: null
        required: true
        type: string
    VPC_OCTETS:
        required: true
        description: the /16 net of the VPC to look for - i.e 10.11.0.0
        default: 10.11.0.0
    REGION:
        default: "INSTANCE::region"
        description: null
        overrides: null
        required: true
        type: null
    PUBLIC_ROUTE_NAME:
        default: test-public-route
        description: null
        overrides: null
        required: true
        type: string
    PUBLIC_SUBNET_NAME:
        default: test-public-subnet
        description: The name of the public subnet you want to create your server in
        overrides: null
        required: true
        type: string
    PUBLIC_SUBNET_NUM_ZONES:
        required: true
        description: How many public subnets to create
        type: number
        default: 3
    VPC_CIDR:
        default: 10.11.0.0/16
        description: The CIDR to match to locate the VPC that this server is to be created in
        overrides: null
        required: true
        type: string
    SERVER_NAME:
        default: simple-server
        description: the name of the server
        required: true
    SERVER_INGRESS_PORTS:
        default:
            - 80
            - 22
        description: Ports to open up in the server security group
        required: true
        type: array
    SERVER_INGRESS_CIDRS:
        default:
            - 0.0.0.0/0
        description: null
        overrides: null
        required: true
        type: array
    SERVER_SIZE:
        default: t2.small
        description: the size of the server to launch
        required: true
    TIMEZONE:
        default: America/Chicago
        value: America/Chicago
        description: the timezone the servers should come up in
        overrides: null
        required: true
        type: string
    VPC_TAGS:
        required: false
        description: tags to apply to the vpc
        type: array
        default: null
    SERVER_AMI:
        description: the ami id of the vpn
        switch: "INSTANCE::region"
        cases:
            us-east-1: ami-c481fad3
            us-east-2: ami-71ca9114
            us-west-1: ami-de347abe
            us-west-2: ami-dd4894bd
            ap-south-1: ami-cacbbea5
            ap-northeast-2: ami-a04297ce
            ap-southeast-1: ami-7243e611
            ap-southeast-2: ami-55d4e436
            ap-northeast-1: ami-1a15c77b
            eu-central-1: ami-0044b96f
            eu-west-1: ami-d41d58a7
            sa-east-1: ami-b777e4db
        type: case
    SERVER_KEYPAIR:
        description: the name of the keypair to launch server with
        require: true
    SUFFIX:
        required: false
        description: when used will use the value to suffix the names of all converged objects
        type: string
    DATADOG_KEY:
        default: null
        value: null
        description: "If you have a datadog key, enter it here and we will install the agent"
        overrides: null
        required: false
